### ISSUE TITLE
I want to design the perfect mate for the 16n

### ISSUE THREAD

**Issue by sapyatkuen** [16n-faderbank/16n#49]
Hi, 

I´m trying to design a mate for the 16n: the **64n**, _3 potentiometers and 1 encoder_ to match each one of the fader. 

How can I figure out what components it will need? Will it work with the Teensy 3.2? I suppose I´d need a small multiplexer for each pot like the 16n has one for each fader but, will the big multiplexer be enough to handle them?

The only outputs it will have are USB and jack for MIDI, no I2C required.

Thanks!

**Comment by infovore** [comment]
> How can I figure out what components it will need? 

I'm guessing what you're asking really is: how do I design the electronic circuit? There isn't really a shortcut here. It just takes time and starting with smaller projects. What you describe isn't exactly a bad project to begin with, although I'd start with a single channel of it to learn some ins/outs.

Potentiometers fed with 3.3V can go straight to a Teensy analog in. Encoders require two input pins per encoder on the MCU, and you'll need a pair of pull-up resistors for every encoder. Once you start adding multiplexers, you'll want power filtering capacitors for multiplexer chips. If you're using a jack for MIDI, you'll also need a couple of resistors there - you can find out the values relatively easily online.

The [schematic](https://github.com/16n-faderbank/16n/blob/master/electronics/16n_schematic.pdf) will give you some clues.

But I can't answer the question further because it's _the work_ of designing such a thing.

> Will it work with the Teensy 3.2? 

You could absolutely built that around a Teensy 3.2

>I suppose I´d need a small multiplexer for each pot like the 16n has one for each fader but, will the big multiplexer be enough to handle them?

There is _one_ multiplexer on the 16n. It takes sixteen analog inputs and routes them to a single pin. To do that, it uses four 'switching' pins, which are set high/low to define which of the sixteen inputs to read from, along with a fifth pin to 'enable' the multiplexer. On 16n, we just leave that fifth pin high all the time.

Multiplexers are easily found in 8 or 16 channel versions. They are quite easy to daisy-chain the pin-select channels on; that means you need four Teensy pins to choose channels 1-16, and then one Teensy pin for every multiplexer.

"Will the big multiplexer be enough to handle them" == I guess you're asking about channel count. No, it won't. Get more, daisy-chain them. The [datasheet for a CD74HC4067](https://www.ti.com/lit/ds/symlink/cd74hc4067.pdf) will give you some hints as to how.

It's a nice idea for a controller. I'd honestly start by trying to make one channel work on a Teensy on your bench with a breadboard and jumper wires.

I'm closing this issue, because it's not an "issue" with 16n.
